apiVersion: apps/v1
kind: Deployment
metadata:
  name: r2r-cc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 866106427415.dkr.ecr.us-west-2.amazonaws.com/eks-demo:latest
          ports:
            - containerPort: 3000
